## Tugas 2

In [1]:
#import pandas and numpy
import pandas as pd
import numpy as np

In [2]:
crime=pd.read_csv("crime.csv")
crime.head()

INCIDENT_ID         OFFENSE_ID  OFFENSE_CODE  OFFENSE_CODE_EXTENSION  \
0   2016376978   2016376978521300          5213                       0   
1  20186000994  20186000994239900          2399                       0   
2  20166003953  20166003953230500          2305                       0   
3    201872333    201872333239900          2399                       0   
4   2017411405   2017411405230300          2303                       0   

                OFFENSE_TYPE_ID       OFFENSE_CATEGORY_ID  \
0  weapon-unlawful-discharge-of          all-other-crimes   
1                   theft-other                   larceny   
2      theft-items-from-vehicle  theft-from-motor-vehicle   
3                   theft-other                   larceny   
4                theft-shoplift                   larceny   

    FIRST_OCCURRENCE_DATE   LAST_OCCURRENCE_DATE          REPORTED_DATE  \
0   6/15/2016 11:31:00 PM                    NaN  6/15/2016 11:31:00 PM   
1  10/11/2017 12:30:00 PM  10/11/2017 4:55:00 PM   1/29/2018 5:53:00 PM   
2     3/4/2016 8:00:00 PM   4/25/2016 8:00:00 AM   4/26/2016 9:02:00 PM   
3    1/30/2018 7:20:00 PM                    NaN  1/30/2018 10:29:00 PM   
4    6/22/2017 8:53:00 PM                    NaN   6/23/2017 4:09:00 PM   

      INCIDENT_ADDRESS      GEO_X      GEO_Y     GEO_LON    GEO_LAT  \
0                  NaN  3193983.0  1707251.0 -104.809881  39.773188   
1                  NaN  3201943.0  1711852.0 -104.781434  39.785649   
2  2932 S JOSEPHINE ST  3152762.0  1667011.0 -104.957381  39.663490   
3  705 S COLORADO BLVD  3157162.0  1681320.0 -104.941440  39.702698   
4       2810 E 1ST AVE  3153211.0  1686545.0 -104.955370  39.717107   

   DISTRICT_ID  PRECINCT_ID             NEIGHBORHOOD_ID  IS_CRIME  IS_TRAFFIC  
0            5          521                   montbello         1           0  
1            5          522  gateway-green-valley-ranch         1           0  
2            3          314                   wellshire         1           0  
3            3          312                     belcaro         1           0  
4            3          311                cherry-creek         1           0

In [3]:
crime.describe() #untuk statdes di phyton

INCIDENT_ID    OFFENSE_ID   OFFENSE_CODE  OFFENSE_CODE_EXTENSION  \
count  4.625140e+05  4.625140e+05  462514.000000           462514.000000   
mean   3.768787e+09  3.768787e+15    3841.317180                0.204474   
std    9.469149e+09  9.469149e+15    1656.022635                0.577986   
min    2.015800e+04  2.015854e+10     902.000000                0.000000   
25%    2.014624e+09  2.014624e+15    2305.000000                0.000000   
50%    2.016503e+09  2.016503e+15    3572.000000                0.000000   
75%    2.018203e+09  2.018203e+15    5441.000000                0.000000   
max    2.018792e+12  2.018792e+18    7399.000000                5.000000   

              GEO_X         GEO_Y        GEO_LON        GEO_LAT  \
count  4.587500e+05  4.587500e+05  458750.000000  458750.000000   
mean   3.162198e+06  1.694853e+06    -104.931834      39.720386   
std    6.508634e+05  1.602382e+05       1.821556       0.689796   
min    3.050128e+06  1.648935e+06    -105.321797       0.000001   
25%    3.138096e+06  1.683027e+06    -105.009022      39.707510   
50%    3.145539e+06  1.694757e+06    -104.982602      39.739773   
75%    3.161705e+06  1.701573e+06    -104.925455      39.758429   
max    4.067476e+07  1.141836e+07      -0.000001      39.904311   

         DISTRICT_ID    PRECINCT_ID       IS_CRIME     IS_TRAFFIC  
count  462514.000000  462514.000000  462514.000000  462514.000000  
mean        3.484173     365.896738       0.739835       0.260684  
std         1.770862     177.799637       0.438725       0.439008  
min         1.000000     111.000000       0.000000       0.000000  
25%         2.000000     213.000000       0.000000       0.000000  
50%         3.000000     323.000000       1.000000       0.000000  
75%         5.000000     521.000000       1.000000       1.000000  
max         7.000000     759.000000       1.000000       1.000000

In [4]:
np.sum(crime.isnull()) #liat data yang missing value

INCIDENT_ID                    0
OFFENSE_ID                     0
OFFENSE_CODE                   0
OFFENSE_CODE_EXTENSION         0
OFFENSE_TYPE_ID                0
OFFENSE_CATEGORY_ID            0
FIRST_OCCURRENCE_DATE          0
LAST_OCCURRENCE_DATE      316100
REPORTED_DATE                  0
INCIDENT_ADDRESS           45487
GEO_X                       3764
GEO_Y                       3764
GEO_LON                     3764
GEO_LAT                     3764
DISTRICT_ID                    0
PRECINCT_ID                    0
NEIGHBORHOOD_ID                0
IS_CRIME                       0
IS_TRAFFIC                     0
dtype: int64

In [7]:
crime['GEO_X']=crime['GEO_X'].fillna(3.162198e+06)
crime['GEO_Y']=crime['GEO_Y'].fillna(1.694853e+06)
crime['GEO_LON']=crime['GEO_LON'].fillna(-104.931834)
crime['GEO_LAT']=crime['GEO_LAT'].fillna(39.720386)
np.sum(crime.isnull())

INCIDENT_ID                    0
OFFENSE_ID                     0
OFFENSE_CODE                   0
OFFENSE_CODE_EXTENSION         0
OFFENSE_TYPE_ID                0
OFFENSE_CATEGORY_ID            0
FIRST_OCCURRENCE_DATE          0
LAST_OCCURRENCE_DATE      316100
REPORTED_DATE                  0
INCIDENT_ADDRESS           45487
GEO_X                          0
GEO_Y                          0
GEO_LON                        0
GEO_LAT                        0
DISTRICT_ID                    0
PRECINCT_ID                    0
NEIGHBORHOOD_ID                0
IS_CRIME                       0
IS_TRAFFIC                     0
dtype: int64

In [9]:
crime['GEO_X']=crime['GEO_X'].fillna((crime['GEO_X'].mean()))
crime['GEO_Y']=crime['GEO_Y'].fillna((crime['GEO_Y'].mean()))
crime['GEO_LON']=crime['GEO_LON'].fillna((crime['GEO_LON'].mean()))
crime['GEO_LAT']=crime['GEO_LAT'].fillna((crime['GEO_LAT'].mean()))
np.sum(crime.isnull())

INCIDENT_ID                    0
OFFENSE_ID                     0
OFFENSE_CODE                   0
OFFENSE_CODE_EXTENSION         0
OFFENSE_TYPE_ID                0
OFFENSE_CATEGORY_ID            0
FIRST_OCCURRENCE_DATE          0
LAST_OCCURRENCE_DATE      316100
REPORTED_DATE                  0
INCIDENT_ADDRESS           45487
GEO_X                          0
GEO_Y                          0
GEO_LON                        0
GEO_LAT                        0
DISTRICT_ID                    0
PRECINCT_ID                    0
NEIGHBORHOOD_ID                0
IS_CRIME                       0
IS_TRAFFIC                     0
dtype: int64

In [11]:
from scipy.stats import mode
#fill missing value with mode for qualitative/categorical data
crime['LAST_OCCURRENCE_DATE']=crime['LAST_OCCURRENCE_DATE'].fillna(crime['LAST_OCCURRENCE_DATE']).dropna().mode()[0]
crime['INCIDENT_ADDRESS']=crime['INCIDENT_ADDRESS'].fillna(crime['INCIDENT_ADDRESS']).dropna().mode()[0]

In [12]:
crime.isnull().sum()

INCIDENT_ID               0
OFFENSE_ID                0
OFFENSE_CODE              0
OFFENSE_CODE_EXTENSION    0
OFFENSE_TYPE_ID           0
OFFENSE_CATEGORY_ID       0
FIRST_OCCURRENCE_DATE     0
LAST_OCCURRENCE_DATE      0
REPORTED_DATE             0
INCIDENT_ADDRESS          0
GEO_X                     0
GEO_Y                     0
GEO_LON                   0
GEO_LAT                   0
DISTRICT_ID               0
PRECINCT_ID               0
NEIGHBORHOOD_ID           0
IS_CRIME                  0
IS_TRAFFIC                0
dtype: int64

In [14]:
crime['LAST_OCCURRENCE_DATE'].mode()
crime['INCIDENT_ADDRESS'].mode()

0    7800 E SMITH RD
dtype: object

In [15]:
##mengatasi outlier
from scipy import stats
z=np.abs(stats.zscore(crime._get_numeric_data()))
print(z)
crime=crime[(z<3).all(axis=1)]
print(crime.shape) #melihat dimensi data

[[0.18506538 0.18506538 0.82830046 ... 0.87234953 0.5930033  0.59380266]
 [1.73376008 1.73376008 0.87095352 ... 0.87797384 0.5930033  0.59380266]
 [1.73164827 1.73164827 0.92771609 ... 0.29188358 0.5930033  0.59380266]
 ...
 [0.18480439 0.18480439 0.96597988 ... 0.30313221 1.68633126 1.68406117]
 [0.18480622 0.18480622 1.0010036  ... 1.37175196 0.5930033  0.59380266]
 [1.73376125 1.73376125 0.92831995 ... 0.29188358 0.5930033  0.59380266]]
(433276, 19)


In [16]:
crime

INCIDENT_ID         OFFENSE_ID  OFFENSE_CODE  OFFENSE_CODE_EXTENSION  \
0        2016376978   2016376978521300          5213                       0   
1       20186000994  20186000994239900          2399                       0   
2       20166003953  20166003953230500          2305                       0   
3         201872333    201872333239900          2399                       0   
4        2017411405   2017411405230300          2303                       0   
5         201872837    201872837549900          5499                       0   
6       20186001015  20186001015230400          2304                       0   
7         201870628    201870628570700          5707                       0   
8         201870833    201870833540100          5401                       0   
9       20186001048  20186001048230500          2305                       0   
10        201872390    201872390357200          3572                       0   
11      20186001033  20186001033230400          2304                       0   
12       2016340553   2016340553230300          2303                       0   
13       2017383968   2017383968240400          2404                       0   
14       2016236602   2016236602230300          2303                       0   
15      20176004695  20176004695230500          2305                       0   
16       2017395809   2017395809240400          2404                       0   
17        201869174    201869174570700          5707                       0   
18        201869047    201869047260900          2609                       0   
19        201871381    201871381544100          5441                       0   
20        201871171    201871171549900          5499                       0   
21        201869050    201869050544100          5441                       0   
22        201872028    201872028540100          5401                       0   
23        201871362    201871362549900          5499                       0   
24        201870800    201870800220300          2203                       0   
25        201871768    201871768279900          2799                       0   
26      20188004580  20188004580131600          1316                       0   
27        201871234    201871234549900          5499                       0   
28       2017294559   2017294559240400          2404                       0   
29       2016398281   2016398281570700          5707                       0   
...             ...                ...           ...                     ...   
462482   2018838504   2018838504240400          2404                       0   
462483  20185005553  20185005553360500          3605                       0   
462484   2018857700   2018857700357200          3572                       0   
462485   2018853002   2018853002549900          5499                       0   
462487  20186012306  20186012306230500          2305                       0   
462488   2018848949   2018848949131300          1313                       0   
462489   2018833780   2018833780540100          5401                       0   
462491   2018831730   2018831730544100          5441                       0   
462492   2018850308   2018850308230500          2305                       0   
462493   2018840372   2018840372299900          2999                       0   
462494  20186011951  20186011951230500          2305                       0   
462495   2018830009   2018830009544100          5441                       0   
462496  20186012075  20186012075230500          2305                       0   
462497   2018852153   2018852153544100          5441                       0   
462498   2018839386   2018839386299901          2999                       1   
462499   2018849302   2018849302549900          5499                       0   
462500   2018844859   2018844859240400          2404                       0   
462501  20186012154  20186012154230500          2305                       0   
462502  

## sumber : https://www.kaggle.com/paultimothymooney/denver-crime-data/version/43